### PR TITLE
fix(engine): os conditions for archlinux

### LINKED ISSUE #223: engine: `utils/os.coffee` is broken for Arch Linux
The `packages/engine/src/utils/os.coffee` utils don't work for Arch Linux anymore:
```
    # Arch Linux
    elif uname -r | egrep 'ARCH$' >/dev/null; then
        OS=arch
        VERSION=`uname -r | sed 's/\\(.*\\)-ARCH/\\1/'`
```
the `uname -r` command doesn't output  with "ARCH" and the condition is never passing

## To reproduce

```
cd packages/engine/env/arch_chroot
docker-compose up
```

errors are like:

```
Error: NIKITA_EXECUTE_EXIT_CODE_INVALID: an unexpected exit code was encountered, command is "ARCH=$(uname -m | sed 's/x86_//;s/i[3-6]86/32/')\n#…", got 2 instead of 0.
```

## Possible solution

I think we need to parse the `/etc/os-release` file to retrieve the linux distribution.

### PR DESCRIPTION
**Pull request by sergkudinov**
closes #223

### CODE REVIEW

File: packages/engine/src/utils/os.coffee [hunk 1]
```diff
@@ -25,9 +25,9 @@ module.exports =
         OS=$DISTRIB_ID
         VERSION=$DISTRIB_RELEASE
     # Arch Linux
-    elif uname -r | egrep 'ARCH$' >/dev/null; then
+    elif cat /etc/os-release | egrep 'arch$' >/dev/null; then
```
Comment (wdavidw) [inline packages/engine/src/utils/os.coffee:28]: If `uname` is here, then why not using uname, this way we could also support other distrib than arch ?

Comment (sergkudinov) [reply packages/engine/src/utils/os.coffee:28]: `uname -r` prints same for all distributions: `4.19.121-linuxkit`. I tested on Centos and Ubuntu. So, we can't use it to determine.

**Review by wdavidw — APPROVED** [review]
centos 6 related conditions shouldn't be in this merge request
