### PR TITLE
fix: schema and lxd environment

### LINKED ISSUE #196: ipa: tests are not passing in the configured environment
Some tests for `@ipa.service` are not passing anymore. The error is like:

```
Error: All nameservers failed to answer the query freeipa.nikita.local. IN A: Server 10.207.177.1 UDP port 53 answered SERVFAIL
      at Proxy.handler (src/service/index.coffee.md:60:17)
```

### Possible cause

The cause might be related to environment installation in `packages/ipa/env/ipa/start.coffee` and changings in `@lxd` package. For example, after migration, to install freeipa on lxd centos/7 container it took changing permissions for `/tmp` folder with `chmod -R 777 /tmp` command, what wasn't a case before.

### To reproduce

```
# Install a VM:
./packages/lxd/bin/cluster start

# Start lxd container
export NIKITA_HOME=/nikita
npx coffee ./packages/ipa/env/ipa/start.coffee

# Run tests
lxc exec freeipa --cwd /nikita/packages/ipa npx mocha test/**/*.coffee
```

### PR DESCRIPTION
**Pull request by sergkudinov**
Closes #196

### CODE REVIEW

File: packages/lxd/test/init.coffee [hunk 1]
```diff
@@ -132,6 +132,7 @@ describe 'lxd.init', ->
         status.should.be.false()
     
     they 'Init new VM', ({ssh}) ->
+      @timeout -1 # sometimes it is downloading another VM image than in before()
```
Comment (wdavidw) [inline packages/lxd/test/init.coffee:135]: new issue

File: packages/lxd/test.sample.coffee [hunk 2]
```diff
@@ -1,11 +1,12 @@
...
   tags:
-    lxd: false
-    lxd_prlimit: false
+    lxd: true
+    lxd_prlimit: true
   ssh: [
     null
-    { host: '127.0.0.1', username: process.env.USER }
+  ,
+    host: '127.0.0.1', username: process.env.USER
```
Comment (wdavidw) [inline packages/lxd/test.sample.coffee:9]: revert

**Review by wdavidw — CHANGES_REQUESTED** [review]
